/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyconverter.ui;

import currencyconverter.uiController.MainPageController;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author musta
 */
public class MainFrame extends javax.swing.JFrame {
    MainPageController mpc = new MainPageController();
    DefaultTableModel modelTable;
    private boolean checkMoney =true;
    private boolean checkCrypto =true;
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() throws SQLException {
        initComponents();
        mpc.setRealValueAll();
        modelTable= (DefaultTableModel) homepage_table.getModel();
        mpc.fillTheTable(modelTable,checkMoney,checkCrypto);
        mpc.fillComboBox(converter_ComboBoxMain);
        mpc.fillComboBox(converter_ComboBoxTarget);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homepage_table = new javax.swing.JTable();
        homepage_TextFieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        homepage_CheckBoxMoney = new javax.swing.JCheckBox();
        homepage_CheckBoxCrypto = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        converter_TextField = new javax.swing.JTextField();
        converter_ComboBoxMain = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        converter_ComboBoxTarget = new javax.swing.JComboBox<>();
        converter_ButtonCalculate = new javax.swing.JButton();
        converter_LabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));

        homepage_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Code", "Type", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        homepage_table.setEnabled(false);
        jScrollPane1.setViewportView(homepage_table);

        homepage_TextFieldSearch.setToolTipText("");
        homepage_TextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_TextFieldSearchActionPerformed(evt);
            }
        });
        homepage_TextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                homepage_TextFieldSearchKeyReleased(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the name or code");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        homepage_CheckBoxMoney.setSelected(true);
        homepage_CheckBoxMoney.setText("Money");
        homepage_CheckBoxMoney.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                homepage_CheckBoxMoneyİtemStateChanged(evt);
            }
        });
        homepage_CheckBoxMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_CheckBoxMoneyActionPerformed(evt);
            }
        });

        homepage_CheckBoxCrypto.setSelected(true);
        homepage_CheckBoxCrypto.setText("Crypto");
        homepage_CheckBoxCrypto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                homepage_CheckBoxCryptoİtemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(homepage_CheckBoxMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(homepage_CheckBoxCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(homepage_TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homepage_CheckBoxMoney)
                    .addComponent(homepage_CheckBoxCrypto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homepage_TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home Page", jPanel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unit you want to convert");

        converter_TextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        converter_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converter_TextFieldActionPerformed(evt);
            }
        });

        converter_ComboBoxMain.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        converter_ComboBoxMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Currency", "Item 2", "Item 3", "Item 4" }));
        converter_ComboBoxMain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                converter_ComboBoxMainİtemStateChanged(evt);
            }
        });
        converter_ComboBoxMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converter_ComboBoxMainActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("To");

        converter_ComboBoxTarget.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        converter_ComboBoxTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Currency", "Item 2", "Item 3", "Item 4" }));

        converter_ButtonCalculate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        converter_ButtonCalculate.setText("Calculate");
        converter_ButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converter_ButtonCalculateActionPerformed(evt);
            }
        });

        converter_LabelResult.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        converter_LabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        converter_LabelResult.setText("$$$");
        converter_LabelResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(converter_ComboBoxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(converter_ButtonCalculate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(converter_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(converter_ComboBoxMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(converter_LabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(converter_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(converter_ComboBoxMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(converter_ButtonCalculate)
                    .addComponent(converter_ComboBoxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(converter_LabelResult)
                .addGap(92, 92, 92))
        );

        jTabbedPane1.addTab("Converter", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void converter_ComboBoxMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converter_ComboBoxMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_converter_ComboBoxMainActionPerformed

    private void homepage_TextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_TextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homepage_TextFieldSearchActionPerformed

    private void homepage_TextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homepage_TextFieldSearchKeyReleased
        String searchKey  = homepage_TextFieldSearch.getText();
        
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(modelTable);
        
        homepage_table.setRowSorter(tableRowSorter);
        
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchKey));     
    }//GEN-LAST:event_homepage_TextFieldSearchKeyReleased

    private void homepage_CheckBoxMoneyİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_homepage_CheckBoxMoneyİtemStateChanged
        String searchKey = homepage_CheckBoxMoney.getText();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            checkMoney = true;
            try {
                mpc.fillTheTable(modelTable,checkMoney,checkCrypto);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
             checkMoney = false;
            try {
                mpc.fillTheTable(modelTable,checkMoney,checkCrypto);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
        }
        
    }//GEN-LAST:event_homepage_CheckBoxMoneyİtemStateChanged

    private void homepage_CheckBoxMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_CheckBoxMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homepage_CheckBoxMoneyActionPerformed

    private void converter_ComboBoxMainİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_converter_ComboBoxMainİtemStateChanged

    }//GEN-LAST:event_converter_ComboBoxMainİtemStateChanged

    private void converter_ButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converter_ButtonCalculateActionPerformed
        String code1 = converter_ComboBoxMain.getSelectedItem().toString();
        String code2 = converter_ComboBoxTarget.getSelectedItem().toString();
        String count = converter_TextField.getText();
        try {
            mpc.converterButton(count,code1, code2, this.converter_LabelResult);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_converter_ButtonCalculateActionPerformed

    private void converter_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converter_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_converter_TextFieldActionPerformed

    private void homepage_CheckBoxCryptoİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_homepage_CheckBoxCryptoİtemStateChanged
        
        
        
        
        
        
        String searchKey = homepage_CheckBoxCrypto.getText();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            checkCrypto = true;
            try {
                mpc.fillTheTable(modelTable,checkMoney,checkCrypto);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
             checkCrypto = false;
             try {
                mpc.fillTheTable(modelTable,checkMoney,checkCrypto);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
        }
    }//GEN-LAST:event_homepage_CheckBoxCryptoİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton converter_ButtonCalculate;
    private javax.swing.JComboBox<String> converter_ComboBoxMain;
    private javax.swing.JComboBox<String> converter_ComboBoxTarget;
    private javax.swing.JLabel converter_LabelResult;
    private javax.swing.JTextField converter_TextField;
    private javax.swing.JCheckBox homepage_CheckBoxCrypto;
    private javax.swing.JCheckBox homepage_CheckBoxMoney;
    private javax.swing.JTextField homepage_TextFieldSearch;
    private javax.swing.JTable homepage_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables


}
